version: "3"
services:
  app:
    image: frontend
    build: ./frontend
    container_name: frontend
    env_file:
      - .env
    ports:
      - "8080:8080"
  web:
    build:
      context: ./backend
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ./backend:/app
      - ./backend/app/logs:/app/logs
    image: pythonweb     
    container_name: backend
    ports:
      - "${PORT}:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env   
volumes:
  postgres_data: